[tool.poetry]
name = "19-2-dz"
version = "0.1.0"
description = ""
authors = ["LQP <homepc@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
