# Generated by Django 4.2.6 on 2023-11-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_preview_alter_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
