# Generated by Django 4.2.6 on 2023-10-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
